var allowedWords = [
   /Sister Act/ig,
   /Barbie And Her Sisters/ig,
   /Hannah and Her Sisters/ig,
   /My Sisters Keeper/ig,
   /The Bronte Sisters/ig,
   /Two Mules For/ig,
   /Your Sisters Sister/ig,
   /A Tale of Two Sisters/ig,
   /Sister Cities/ig,
   /Sister Wives/ig,
   /Overcome Porn Addiction/ig,
   /Breakfree End Porn Addiction/ig,
   /Porn Addiction Cure/ig,
   /Xander/ig,
   /Ultimate Guide/ig,
   /Modern Guide/ig,
   /Illustrated Guide/ig,
   /Complete Guide/ig,
   /Sex And The City/ig,
   /Enlightened Sex Manual/ig,
   /Sex on the Brain/ig,
   /Daddy Yankee/ig,
   /Sex Lies and Love Bites/ig,
   /Invisible Sister/ig,
   /Sister Location/ig,
   /Sister_Location/ig,
   /Sister.Location/ig,
   /Instinct Guide/ig,
   /Analytics/ig,
   /Analysis/ig,
   /Analog/ig,
   /Analytic/ig,
   /Analogy/ig,
   /Analyzing/ig,
   /Dr.Soc/ig,
   /poverty/ig,
   /PBS/ig,
   /PSYCHD/ig,
   /The Sisters Who Have Too Many Things Happening/ig,
   /Parks and Recreation/ig,
   /The Testament of Sister New Devil/ig,
   /Cock sparrer/ig,
   /YTS.AM/ig,
   //ig,
   //ig,
   //ig,
   //ig,
   //ig,
]