var blockedStars = [
		/Abella Danger/ig,
		/Adrianna Luna/ig,
		/Alana Evans/ig,
		/Aletta Ocean/ig,
		/Alex Taylor/ig,
		/Alexandra Quinn/ig,
		/Amber Lynn/ig,
		/Amber Rayne/ig,
		/Amy Fisher/ig,
		/Andrea True/ig,
		/Anikka Albrite/ig,
		/Anna Malle/ig,
		/Annette Haven/ig,
		/Annie Sprinkle/ig,
		/April Flores/ig,
		/Asa Akira/ig,
		/Ashley Blue/ig,
		/Asia Carrera/ig,
		/Audrey Hollander/ig,
		/August Ames/ig,
		/Aurora Snow/ig,
		/Belladonna/ig,
		/Belle Knox/ig,
		/BiBi Jones/ig,
		/Bodil Joensen/ig,
		/Bonnie Rotten/ig,
		/Brandi Love/ig,
		/Bree Olson/ig,
		/Bridgette Kerkove/ig,
		/Brigitte Lahaie/ig,
		/Brittany Andrews/ig,
		/Brittany O'Connell/ig,
		/Brooklyn Lee/ig,
		/C\. J\. Laing/ig,
		/Calli Cox/ig,
		/Candida Royalle/ig,
		/Candy Barr/ig,
		/Capri Anderson/ig,
		/Cara Lott/ig,
		/Carol Connors/ig,
		/Casey Calvert/ig,
		/Charmane Star/ig,
		/Chasey Lain/ig,
		/Chloe Jones/ig,
		/Clara Morgane/ig,
		/Daisy Marie/ig,
		/Dana DeArmond/ig,
		/Dana Vespoli/ig,
		/Dani Daniels/ig,
		/Debi Diamond/ig,
		/Dillion Carter/ig,
		/Erica Boyer/ig,
		/Estelle Desanges/ig,
		/Flower Tucci/ig,
		/Francesca Le/ig,
		/Gauge/ig,
		/Georgina Spelvin/ig,
		/Ginger Lynn/ig,
		/Gloria Leonard/ig,
		/Gracie Glam/ig,
		/Heather Hunter/ig,
		/Hillary Scott/ig,
		/Holly Ryder/ig,
		/Houston/ig,
		/Ilona Staller/ig,
		/Cicciolina/ig,
		/Jasmin St. Claire/ig,
		/Jeannie Pepper/ig,
		/Jenaveve Jolie /ig,
		/Jenna Haze/ig,
		/Jenna Jameson/ig,
		/Jenna Presley/ig,
		/Jesse Jane/ig,
		/Jessie Andrews/ig,
		/Jessie Rogers/ig,
		/Joanna Angel/ig,
		/Juliet Anderson/ig,
		/Justine Joli/ig,
		/Kaitlyn Ashley/ig,
		/Kandi Barbour/ig,
		/Karen Summer/ig,
		/Katie Cummings/ig,
		/Katie Morgan/ig,
		/Katja Kassin/ig,
		/Katsuni/ig,
		/Kay Parker/ig,
		/Kaylani Lei/ig,
		/Kendra Lust/ig,
		/Keri Sable/ig,
		/Kimberly Kane/ig,
		/Kleio Valentien/ig,
		/Kylie Ireland/ig,
		/Lana Rhoades/ig,
		/Leilani Leeane/ig,
		/Lilly Rader/ig,
		/Linda Lovelace/ig,
		/Linda Wong/ig,
		/Lisa Ann/ig,
		/Lizz Tayler/ig,
		/Lolo Ferrari/ig,
		/Lupe Fuentes/ig,
		/Maddy O'Reilly/ig,
		/Mai Lin/ig,
		/Mandy Flores/ig,
		/Marilyn Chambers/ig,
		/Marlene Willoughby/ig,
		/Mary Carey/ig,
		/Mary Millington/ig,
		/Marylin Star/ig,
		/May Ling Su/ig,
		/Melissa Hill/ig,
		/Mia Khalifa/ig,
		/Mia Malkova/ig,
		/Midori/ig,
		/Mika Tan/ig,
		/Mimi Miyagi/ig,
		/Missy/ig,
		/Moana Pozzi/ig,
		/Monique Alexander/ig,
		/Nikita Denise/ig,
		/Nikki Benz/ig,
		/Nikki Charm/ig,
		/Nikki Dial/ig,
		/Nina Hartley/ig,
		/Nina Roberts/ig,
		/Porsche Lynn/ig,
		/Prinzzess/ig,
		/Priya Rai/ig,
		/Raylene/ig,
		/Rebecca Brooke/ig,
		/Rebecca Lord/ig,
		/Remy LaCroix/ig,
		/Rene Bond/ig,
		/Riley Reid/ig,
		/Riley Steele/ig,
		/Robin Byrd/ig,
		/Rosa Caracciolo/ig,
		/Sasha Grey/ig,
		/Savannah/ig,
		/Seka/ig,
		/Sharon Mitchell/ig,
		/Shauna Grant/ig,
		/Shyla Jennings/ig,
		/Shyla Stylez/ig,
		/Sinn Sage/ig,
		/Stacey Donovan/ig,
		/Stormy Daniels/ig,
		/Sunny Leone/ig,
		/Tabatha Cash/ig,
		/Taylor St. Claire/ig,
		/Taylor Wane/ig,
		/Teagan Presley/ig,
		/Tera Patrick/ig,
		/Tericka Dye/ig,
		/Tiffany Hopkins/ig,
		/Traci Lords/ig,
		/Trinity Loren/ig,
		/Valentina Nappi/ig,
		/Vanessa Blue/ig,
		/Vanessa del Rio/ig,
		/Vicky Vette/ig,
		/Molly Jane/ig,
		/Xev Bellringer/ig,
		/Lana Rhoades/ig,
		/Tara Tainton/ig,
		/Marley Brinx/ig,
		/Blake Eden/ig,
		/Harley Jameson/ig,
		/Adriana Chechik/ig,
		/Kylie Page/ig,
		/Bree Daniels/ig,
		/Alexis Texas/ig,
		/Eveline Dellai/ig,
		/Cassie Fire/ig,
		/Silvia Dellai/ig,
		//ig,
		//ig,
		//ig,
		//ig,
		//ig,
		//ig,
		//ig,
		//ig,
		//ig,
		//ig,
]