var blockedWords = [
            /Pussy/ig,
            /Anal/ig,
            /Dick/ig,
            /Porn/ig,
            /Incest/ig,
            /Fuck/ig,
            /Sister/ig,
            /Cock/ig,
            /Stepmom/ig,
            /Mommy/ig,
            /Mommies/ig,
            /Milf/ig,
            /Adult/ig,
            /Split Scenes/ig,
            /Raped/ig,
            /Pornstar/ig,
            /Pentyhose/ig,
            /Hentai/ig,
            /SiteRip/ig,
            /18\+/ig,
            /\+18/ig,
            /Bestiality/ig,
            /Squirt/ig,
            /CFNM/ig,
            /Creampie/ig,
            /Cuckold/ig,
            /Fisting/ig,
            /Erotica/ig,
            /Wetlook/ig,
            /Double Penetration/ig,
            /Big[a-z ]*Sis/ig,
            /lil[a-z ]*Sis/ig,
            /Fetish/ig,
            /big[a-z ]*ass/ig,
            /Breast/ig,
            /xxx/ig,
            /H-Game/ig,
            /H Game/ig,
            /Deepthroat/ig,
            /desi[a-z \[]*scandal/ig,
            /scandal[a-z \[]*desi/ig,
            /scandal[a-z \[]*indian/ig,
            /indian[a-z \[]*scandal/ig,
            /Sibling/ig,
            /lesbian/ig,
            /Harem/ig,
            /orgy/ig,
            /nude/ig,
            /Cumshot/ig,
            //ig,
            //ig,
            //ig,
            //ig,

]