var blockedCompanies = [
	/1000Facials/ig,
	/18OnlyGirls/ig,
	/18YearsOld/ig,
	/21EroticAnal/ig,
	/21FootArt/ig,
   /21Naturals/ig,
	/2ChicksSameTime/ig,
	/40SomethingMag/ig,
	/8thStreetLatinas/ig,
	/AbuseMe/ig,
	/Airerose/ig,
	/AlexLegend/ig,
	/AllInternal/ig,
	/AllOver30/ig,
	/Allure Films/ig,
	/Almerias/ig,
	/AmateurAllure/ig,
	/AmericanDaydreams/ig,
	/Anal-Angels/ig,
	/Anal-Beauty/ig,
	/AnalCollege/ig,
	/AnalOverdose/ig,
	/AnalTeenAngels/ig,
	/Analized/ig,
	/Anilos/ig,
	/ArabsExposed/ig,
	/Arch Angel/ig,
	/ArchAngel/ig,
	/Asian1On1/ig,
	/AsianStreetMeat/ig,
	/AssMasterpiece/ig,
	/AssParade/ig,
	/AssTraffic/ig,
	/AssholeFever/ig,
	/Assylum/ig,
	/BFFs/ig,
	/BLACKED/ig,
	/BRAZZERS/ig,
	/BSkow/ig,
	/Babes in Pornland/ig,
	/Babes/ig,
	/BabyGotBoobs/ig,
	/BackRoomFacials/ig,
	/BackroomCastingCouch/ig,
	/BadMilfs/ig,
	/Baeb/ig,
	/BangBros/ig,
	/BangBros18/ig,
	/BangBrosClips/ig,
	/BangBus/ig,
	/BangBusBrickYates/ig,
	/BangPOV/ig,
	/Barely Legal/ig,
	/Beauty4K/ig,
	/BeautyAndTheSenior/ig,
	/BigButtsLikeItBig/ig,
	/BigGulpGirls/ig,
	/BigNaturals/ig,
	/BigTitsAtSchool/ig,
	/BigTitsAtWork/ig,
	/BigTitsInSports/ig,
	/BigTitsLikeBigDicks/ig,
	/BigTitsRoundAsses/ig,
	/BigWetButts/ig,
	/BitchConfessions/ig,
	/BitchesAbroad/ig,
	/BlackIsBetter/ig,
	/BlackLoads/ig,
	/BlackMeatWhiteFeet/ig,
	/Blacked/ig,
	/Blacks On Blondes/ig,
	/BlacksOnBlondes/ig,
	/BlacksOnCougars/ig,
	/BlacksOnMoms/ig,
	/Blazed Studios/ig,
	/BluePillMen/ig,
	/BoldlyGirls/ig,
	/BoxTruckSex/ig,
	/BraZZers/ig,
	/Brazzers/ig,
	/BrazzersExxtra/ig,
	/BreakingAsses/ig,
	/BrickYates/ig,
	/BrokeModel/ig,
	/BrownBunnies/ig,
	/BrutalCastings/ig,
	/BrutalInvasion/ig,
	/BrutalX/ig,
	/BumsBuero/ig,
	/BumsBus/ig,
	/BurningAngel/ig,
	/ButtFormation/ig,
	/ButtPlays/ig,
	/CLIPS4SALE/ig,
	/CarneDelMercado/ig,
	/CastingAllaItaliana/ig,
	/CastingCouch/ig,
	/CastingCouch-X/ig,
	/CherryPimps/ig,
	/ChicasLoca/ig,
	/Clips4Sale/ig,
	/ClubSandy/ig,
	/CockNinjaStudios/ig,
	/CocksXL/ig,
	/Colette/ig,
	/ColombiaFuckFest/ig,
	/CoupleFantasies/ig,
	/Creampie-Angels/ig,
	/CuckoldSessions/ig,
	/Culioneros/ig,
	/CumFiesta/ig,
	/CumForCover/ig,
	/CumLouder/ig,
	/CumPerfection/ig,
	/CzechCasting/ig,
	/CzechCouples/ig,
	/DD Busty/ig,
	/DDFBusty/ig,
	/DPFanatics/ig,
	/DadCrush/ig,
	/DaneJones/ig,
	/DareDorm/ig,
	/Dark X/ig,
	/DarkX/ig,
	/Daughter Swap/ig,
	/DaughterSwap/ig,
	/DayWithAPornstar/ig,
	/DeepThroatSirens/ig,
	/Defloration/ig,
	/Desire Films/ig,
	/Desperate Pleasures/ig,
	/Devils Film/ig,
	/Diabolic Video/ig,
	/Digital Playground/ig,
	/Digital Sin/ig,
	/DigitalPlayground/ig,
	/DirtyMasseur/ig,
	/DirtyWivesClub/ig,
	/DoctorAdventures/ig,
	/Dog House Digital/ig,
	/DogHouseDigital/ig,
	/DollyLittleXXX/ig,
	/DontBreakMe/ig,
	/DontFuckMyDaughter/ig,
	/Dyked/ig,
	/EbonySexTapes/ig,
	/Elegant Angel/ig,
	/ElegantAnal/ig,
	/Erotica X/ig,
	/EroticaX/ig,
	/EuroSexParties/ig,
	/EuroTeenErotica/ig,
	/EverythingButt/ig,
	/Evil Angel/ig,
	/Ex-Girlfriends/ig,
	/Exotic4K/ig,
	/Exploited18/ig,
	/ExploitedCollegeGirls/ig,
	/ExposedCasting/ig,
	/ExxxtraSmall/ig,
	/FTVGirls/ig,
	/FacialAbuse/ig,
	/Fake Taxi/ig,
	/FakeAgent/ig,
	/FakeAgent/ig,
	/FakeAgentUK/ig,
	/FakeCop/ig,
	/FakeShooting/ig,
	/FakeTaxi/ig,
	/FameDigital/ig,
	/Family Therapy/ig,
	/FamilyLust/ig,
	/FamilyStrokes/ig,
	/Fansadox/ig,
	/FantasyHD/ig,
	/FantasyMassage/ig,
	/Fappening/ig,
	/Fapulous/ig,
	/FemaleAgent/ig,
	/FemdomEmpire/ig,
	/FirstAnalDate/ig,
	/FirstAnalQuest/ig,
	/FirstBGG/ig,
	/FirstTimeAuditions/ig,
	/FitnessRooms/ig,
	/FootFetishDaily/ig,
	/Forbidden Affairs/ig,
	/Forbidden Fruits/ig,
	/FuckStudies/ig,
	/FuckedInTraffic/ig,
	/FuckySucky/ig,
	/GFRevenge/ig,
	/GangbangCreampie/ig,
	/GapeLand/ig,
	/GingerPatch/ig,
	/Girls Do Porn/ig,
	/Girls do porn/ig,
	/GirlsDoPorn/ig,
	/GloryHole/ig,
	/GrandpasFuckTeens/ig,
	/HDLove/ig,
	/HDMassagePorn/ig,
	/HandsOnHardcore/ig,
	/Hard X/ig,
	/HardX/ig,
	/HardcoreGangbang/ig,
	/HeavyOnHotties/ig,
	/Hegre-Art/ig,
	/HelplessTeens/ig,
	/HerLimit/ig,
	/Holed/ig,
	/HookupHotshot/ig,
	/HotAndMean/ig,
	/HotAndMean/ig,
	/HotLegsAndFeet/ig,
	/HouseOfTaboo/ig,
	/Housewife1On1/ig,
	/IAmEighteen/ig,
	/IHaveAWife/ig,
	/IKnowThatGirl/ig,
	/ImmoralLive/ig,
	/IndustryInvaders/ig,
	/Innocent High/ig,
	/InnocentHigh/ig,
	/InterracialBlowbang/ig,
	/InterracialPickups/ig,
	/JamesDeen/ig,
	/JesseLoadsMonsterFacials/ig,
	/JimSlip/ig,
	/Joymii/ig,
	/Jules Jordan/ig,
	/JulesJordan/ig,
	/KarupsHA/ig,
	/KarupsPC/ig,
	/KellyMadison/ig,
	/Killergram/ig,
	/KinkyFamily/ig,
	/KinkyInLaws/ig,
	/KinkySpa/ig,
	/LANewGirl/ig,
	/LaCochonne/ig,
	/LaNovice/ig,
	/LasFolladoras/ig,
	/LatinaSexTapes/ig,
	/LegalPorno/ig,
	/LethalHardcore/ig,
	/LetsTryAnal/ig,
	/LivingWithAPornstar/ig,
	/LosConsoladores/ig,
	/Lubed/ig,
	/MMPNetwork/ig,
	/MakeHimCuckold/ig,
	/ManyVids/ig,
	/MassageCreep/ig,
	/MassageRooms/ig,
	/MeetSuckAndFuck/ig,
	/MikesApartment/ig,
	/MilfHunter/ig,
	/MilfsLikeItBig/ig,
	/MissaX/ig,
	/Mofos/ig,
	/MomKnowsBest/ig,
	/MomPov/ig,
	/MomXXX/ig,
	/MommyBlowsBest/ig,
	/MommyGotBoobs/ig,
	/MomsBangTeens/ig,
	/MomsInControl/ig,
	/MomsInControl/ig,
	/MomsLickTeens/ig,
	/MomsTeachSex/ig,
	/MoneyTalks/ig,
	/MonsterCurves/ig,
	/MonstersOfCock/ig,
	/MontysPOV/ig,
	/MormonGirlz/ig,
	/MrStrokesXXX/ig,
	/MrsCreampie/ig,
	/MyBabysittersClub/ig,
	/MyDadsHotGirlfriend/ig,
	/MyDaughtersHotFriend/ig,
	/MyDirtyMaid/ig,
	/MyFirstPublic/ig,
	/MyFirstSexTeacher/ig,
	/MyFriendsHotGirl/ig,
	/MyFriendsHotMom/ig,
	/MyGirlLovesAnal/ig,
	/MyGirlfriendsBustyFriend/ig,
	/MyMilfBoss/ig,
	/MyNaughtyAlbum/ig,
	/MySistersHotFriend/ig,
	/MyVeryFirstTime/ig,
	/MyWifeIsMyPornstar/ig,
	/MyWifesHotFriend/ig,
	/Naughty America/ig,
	/NaughtyAmerica/ig,
	/NaughtyAthletics/ig,
	/NaughtyBookworms/ig,
	/NaughtyOffice/ig,
	/NaughtyRichGirls/ig,
	/NeighborAffair/ig,
	/NetVideoGirls/ig,
	/New Sensations/ig,
	/NewSensations/ig,
	/NoBoring/ig,
	/Nubile/ig,
	/NubileFilms/ig,
	/Nubiles-Porn/ig,
	/Nude Magazine/ig,
	/NuruMassage/ig,
	/OfficeObsession/ig,
	/OnlyBlowJob/ig,
	/OnlyTeenBlowJobs/ig,
	/OperacionLimpieza/ig,
	/OralOverdose/ig,
	/OyeLoca/ig,
	/POV/ig,
	/POVBitch/ig,
	/POVD/ig,
	/POVLife/ig,
	/Passion-HD/ig,
	/PennyPaxLive/ig,
	/Penthouse/ig,
	/Perfect Gonzo/ig,
	/PervsOnPatrol/ig,
	/PervyOnes/ig,
	/Petite18MomPov/ig,
	/PetiteHDPorn/ig,
	/PixAndVideo/ig,
	/Playboy/ig,
	/Porn Pros/ig,
	/PornFidelity/ig,
	/PornMegaLoad/ig,
	/PornPros/ig,
	/PornstarCamHouse/ig,
	/PornstarPlatinum/ig,
	/PornstarVote/ig,
	/PornstarsLikeItBig/ig,
	/PovAngels/ig,
	/PrettyDirty/ig,
	/Private Gold/ig,
	/PrivateCasting-X/ig,
	/PrivateSociety/ig,
	/PropertySex/ig,
	/PublicAgent/ig,
	/PublicDisgrace/ig,
	/PublicPickUps/ig,
	/PublicPickUps/ig,
	/PunishTeens/ig,
	/Pure Passion/ig,
	/Pure18/ig,
	/PureMature/ig,
	/RKPrime/ig,
	/ReadyOrNotHereICum/ig,
	/RealExGirlfriends/ig,
	/RealWifeStories/ig,
	/Reality Kings/ig,
	/RealityJunkies/ig,
	/Relaxxxed/ig,
	/RodneyMoore/ig,
	/RoundAndBrown/ig,
	/RoundJuicyButts/ig,
	/Savita Bhabhi/ig,
	/SchoolgirlInternal/ig,
	/ScoreLand/ig,
	/ScrewBox/ig,
	/SeducedByACougar/ig,
	/SellYourGF/ig,
	/Sex Art/ig,
	/SexAndSubmission/ig,
	/SexArt/ig,
	/SexuallyBroken/ig,
	/ShareMyBF/ig,
	/SheWillCheat/ig,
	/ShesNew/ig,
	/ShootOurself/ig,
	/Shoplyfter/ig,
	/SimplyAnal/ig,
	/SinfulXXX/ig,
	/SinsLife/ig,
	/Sis Loves Me/ig,
	/SisLovesMe/ig,
	/SneakySex/ig,
	/Spizoo/ig,
	/SpoofPorn/ig,
	/SpyFam/ig,
	/SpyPov/ig,
	/StepMomLessons/ig,
	/StepSiblingsCaught/ig,
	/StraightInTheAss/ig,
	/StrandedTeens/ig,
	/StreetBlowJobs/ig,
	/StunningButts/ig,
	/Suicide Girl/ig,
	/SwallowSalon/ig,
	/Swallowed/ig,
	/Sweet Sinner/ig,
	/Sweet18/ig,
	/SweetSinner/ig,
	/Sweetheart Video/ig,
	/Sweetheart Video/ig,
	/TabooFantasy/ig,
	/TakeVan/ig,
	/TeacherFucksTeens/ig,
	/Team Skeet/ig,
	/TeamSkeet/ig,
	/TeamSkeetExtras/ig,
	/TeasePOV/ig,
	/TeenAnalCasting/ig,
	/TeenCurves/ig,
	/TeenFidelity/ig,
	/TeenPies/ig,
	/TeenSexMania/ig,
	/TeenSexMovs/ig,
	/TeensDoPorn/ig,
	/TeensInTheWoods/ig,
	/TeensLikeItBig/ig,
	/TeensLoveAnal/ig,
	/TeensLoveBlackCocks/ig,
	/TeensLoveHugeCocks/ig,
	/TeensLoveMoney/ig,
	/TeenyPlayground/ig,
	/TheArtPorn/ig,
	/TheRealWorkout/ig,
	/TheTrainingofO/ig,
	/TheUpperFloor/ig,
	/TheWhiteBoxxx/ig,
	/TheyDrunk/ig,
	/Third Degree Films/ig,
	/ThisGirlSucks/ig,
	/Throated/ig,
	/Tiny4K/ig,
	/TittyAttack/ig,
	/TonightsGirlfriend/ig,
	/TrickyOldTeacher/ig,
	/TryTeens/ig,
	/TuVenganza/ig,
	/Tushy/ig,
	/Twistys/ig,
	/TwistysHard/ig,
	/UpHerAsshole/ig,
	/VIPissy/ig,
	/VanGoren/ig,
	/Velamma/ig,
	/VelvetEcstasy/ig,
	/VirtualTaboo/ig,
	/VirtualXPorn/ig,
	/Vixen/ig,
	/VoyeurDoctor/ig,
	/WatchingMyDaughterGoBlack/ig,
	/WeFuckBlackGirls/ig,
	/WeLikeToSuck/ig,
	/WeLiveTogether/ig,
	/WhiteTeensBlackCocks/ig,
	/WifeysWorld/ig,
	/WildOnCam/ig,
	/WivesOnVacation/ig,
	/WowGirls/ig,
	/WowPorn/ig,
	/X-Angels/ig,
	/X-Art/ig,
	/XXXPawn/ig,
	/XXXShades/ig,
	/YoungCourtesans/ig,
	/YoungSexParties/ig,
	/ZZSeries/ig,
	/Zero Tolerance/ig,
	/ZeroTolerance/ig,
	/Zoliboy/ig,
	/almerias/ig,
	/Taboo-Fantasy/ig,
	/thz.la/ig,
	/Brothas/ig,
	/GentleDesire/ig,
	/BitchesAbroad/ig,
	/porno-island/ig,
	/artofzoo/ig,
	/Digital Desire/ig,
	/Incezt/ig,
	/ALSScan/ig,
	/BlacksOnSluts/ig,
	/PoRO petit/ig,
	/BigMouthfuls/ig,
	/fakku/ig,
	/SecretCrush/ig,
	/ScoreHD/ig,
	/BareBackStudios/ig,
	/Submissived/ig,
	/Jezebeth/ig,
	//ig,
	//ig,
	//ig,
	//ig,
	//ig,
	//ig,
	//ig,
	
]